//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace podgotovka
{
    using System;
    using System.Collections.Generic;
    
    public partial class packageSize
    {
        public int id { get; set; }
        public Nullable<int> width_centimetr { get; set; }
        public Nullable<int> height_centimetr { get; set; }
        public Nullable<int> length_centimetr { get; set; }
    }
}
