//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace podgotovka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Товар_В_Заказе = new HashSet<Товар_В_Заказе>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Пользователь { get; set; }
        public Nullable<System.DateTime> Дата_заказа { get; set; }
        public Nullable<double> Итоговая_стоймость { get; set; }
        public Nullable<int> Статус { get; set; }
    
        public virtual Пользователь Пользователь1 { get; set; }
        public virtual Статус_Заказа Статус_Заказа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Товар_В_Заказе> Товар_В_Заказе { get; set; }
    }
}
